version: '3.8'

services:
  api:
    image: fazilfizo/express-mongo-api:latest
    environment:
      -MONGO-URI: mongodb+srv://fazil:fazil3456@cluster0.c0zuz3v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      -NODE-ID: api-server
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  frontend1:
    image: fazilfizo/express-mongo-api:v2
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_NODE_ID=frontend1
    ports:
      - "3003:5173"
    networks:
      - app-network

  frontend2:
    image: fazilfizo/express-mongo-api:v2
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_NODE_ID=frontend2
    ports:
      - "3004:5173"
    networks:
      - app-network
      
  frontend3:
    image: fazilfizo/express-mongo-api:v2
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_NODE_ID=frontend3
    ports:
      - "3005:5173"
    networks:
      - app-network

  loadbalancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: