version: '3.8'

services:
  # Load Balancer
  lb:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - app-network

  # Frontend instances (3 replicas)
  frontend1:
    build: ./frontend-UI
    environment:
      - NODE_ID=frontend1
    networks:
      - app-network
    depends_on:
      - api

  frontend2:
    build: ./frontend-UI
    environment:
      - NODE_ID=frontend2
    networks:
      - app-network
    depends_on:
      - api

  frontend3:
    build: ./frontend-UI
    environment:
      - NODE_ID=frontend3
    networks:
      - app-network
    depends_on:
      - api

  # Your existing API service
  api:
    build: .
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: mongodb+srv://fazil:fazil3456@cluster0.c0zuz3v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    command: sh -c "node seed.js && node index.js"
    restart: unless-stopped
    networks:
      - app-network

  # Local MongoDB (optional - you're using Atlas)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge