version: '3.8'

services:
  api:
    build: .
    environment:
      -MONGO-URI: mongodb+srv://fazil:fazil3456@cluster0.c0zuz3v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  frontend1:
    image: yourdockerhubusername/frontend-ui
    environment:
      - PORT=3003
      - REACT_APP_API_URL=http://api:3000
    ports:
      - "3003:3003"
    networks:
      - frontend
      - backend

  frontend2:
    image: yourdockerhubusername/frontend-ui
    environment:
      - PORT=3004
      - REACT_APP_API_URL=http://api:3000
    ports:
      - "3004:3004"
    networks:
      - frontend
      - backend

  frontend3:
    image: yourdockerhubusername/frontend-ui
    environment:
      - PORT=3005
      - REACT_APP_API_URL=http://api:3000
    ports:
      - "3005:3005"
    networks:
      - frontend
      - backend

  loadbalancer:
    build: ./load-balancer
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mongo-data: