version: '3.8'

services:
  api:
    image: fazilfizo/express-mongo-api:latest
    environment:
      -MONGO-URI: mongodb+srv://fazil:fazil3456@cluster0.c0zuz3v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      -NODE-ID: api-server
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  frontend1:
    image: fazilfizo/express-mongo-api:latest
    environment:
      - PORT=3003
      - VITE_API_URL=http://api:3000
      - VITE_NODE_ID=frontend1
      - PORT=5173
    ports:
      - "3003:5173"
    networks:
      - frontend
      - backend

  frontend2:
    image: fazilfizo/express-mongo-api:latest
    environment:
      - PORT=3004
      - VITE_API_URL=http://api:3000
      - VITE_NODE_ID=frontend2
      - PORT=5173
    ports:
      - "3004:5173"
    networks:
      - frontend
      - backend

  frontend3:
    image: fazilfizo/express-mongo-api:latest
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_NODE_ID=frontend3
      - PORT=5173
    ports:
      - "3005:5173"
    networks:
      - frontend
      - backend

  loadbalancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
  backend:
    driver: bridge

volumes:
  mongo-data: